/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PesonalCard {
        "firstName": string;
        "lastName": string;
        "photo": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPesonalCardElement extends Components.PesonalCard, HTMLStencilElement {
    }
    var HTMLPesonalCardElement: {
        prototype: HTMLPesonalCardElement;
        new (): HTMLPesonalCardElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "pesonal-card": HTMLPesonalCardElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PesonalCard {
        "firstName"?: string;
        "lastName"?: string;
        "photo"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "pesonal-card": PesonalCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "pesonal-card": LocalJSX.PesonalCard & JSXBase.HTMLAttributes<HTMLPesonalCardElement>;
        }
    }
}
